{% set name = "pymorphy2" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d4dc611f1aad8cd13c10b6a47c2d301c8321640534d9b3df563e28b3b28d2581

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pymorphy = pymorphy2.cli:main

requirements:
  host:
    - pip
    - python
  run:
    - dawg-python >=0.7
    - docopt >=0.6
    - pymorphy2-dicts-ru >=2.4
    - python

test:
  imports:
    - pymorphy2
    - pymorphy2.opencorpora_dict
    - pymorphy2.units

about:
  home: https://github.com/kmike/pymorphy2/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Morphological analyzer (POS tagger + inflection engine) for Russian language.
  doc_url: https://pymorphy2.readthedocs.org/

extra:
  recipe-maintainers:
    - benhuff
    - oblute
    - mwilson8
